// Generated by ReScript, PLEASE EDIT WITH CARE

import * as StdbTransportMjs from "./StdbTransport.mjs";

function normalizeRow(prim) {
  return StdbTransportMjs.normalizeRow(prim);
}

function encodeStdbValue(prim) {
  return StdbTransportMjs.encodeStdbValue(prim);
}

function encodeIdentityHex(prim) {
  return StdbTransportMjs.encodeIdentityHex(prim);
}

export {
  normalizeRow,
  encodeStdbValue,
  encodeIdentityHex,
}
/* ./StdbTransport.mjs Not a pure module */
