// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Stdlib_JsError from "@rescript/runtime/lib/es6/Stdlib_JsError.js";
import * as Stdlib_Promise from "@rescript/runtime/lib/es6/Stdlib_Promise.js";
import * as Sdk from "spacetimedb/sdk";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";

let serverConnectionConfig = {
  contents: undefined
};

let serverConnectionPromise = {
  contents: undefined
};

let serverConnection = {
  contents: undefined
};

function disconnectIfActive() {
  let conn = serverConnection.contents;
  if (conn === undefined) {
    return;
  }
  let conn$1 = Primitive_option.valFromOption(conn);
  if (conn$1.isActive) {
    conn$1.disconnect();
    return;
  }
}

function connectServerConnection(config) {
  let allTables = config.allTables;
  let timeoutMs = Stdlib_Option.getOr(config.connectTimeoutMs, 10000);
  let builder = new Sdk.DbConnectionBuilder(config.remoteModule, dbConfig => new Sdk.DbConnectionImpl(dbConfig)).withUri(config.uri).withDatabaseName(config.databaseName);
  let connectPromise = new Promise((resolve, reject) => {
    let settled = {
      contents: false
    };
    let resolveOnce = conn => {
      if (settled.contents) {
        return;
      } else {
        settled.contents = true;
        return resolve(conn);
      }
    };
    let rejectOnce = error => {
      if (settled.contents) {
        return;
      } else {
        settled.contents = true;
        disconnectIfActive();
        return reject(error);
      }
    };
    builder.onConnect(conn => {
      try {
        if (allTables === undefined) {
          return resolveOnce(conn);
        }
        if (allTables.length === 0) {
          return resolveOnce(conn);
        }
        let queries = allTables.map(tableName => `SELECT * FROM ` + tableName);
        conn.subscriptionBuilder().onApplied(() => resolveOnce(conn)).onError((_ctx, error) => rejectOnce(error)).subscribe(queries);
        return;
      } catch (raw_jsExn) {
        let jsExn = Primitive_exceptions.internalToException(raw_jsExn);
        if (jsExn.RE_EXN_ID === "JsExn") {
          return rejectOnce(jsExn._1);
        } else {
          return rejectOnce(jsExn);
        }
      }
    }).onConnectError((_ctx, error) => rejectOnce(error));
    try {
      let conn = builder.build();
      serverConnection.contents = Primitive_option.some(conn);
      return;
    } catch (raw_jsExn) {
      let jsExn = Primitive_exceptions.internalToException(raw_jsExn);
      if (jsExn.RE_EXN_ID === "JsExn") {
        return rejectOnce(jsExn._1);
      } else {
        return rejectOnce(jsExn);
      }
    }
  });
  let timeoutMs$1 = timeoutMs;
  if (timeoutMs$1 === undefined) {
    return connectPromise;
  }
  if (timeoutMs$1 === 0) {
    return connectPromise;
  }
  if (timeoutMs$1 < 0) {
    return connectPromise;
  }
  let timeoutPromise = new Promise((_resolve, reject) => {
    setTimeout(() => reject(Primitive_exceptions.internalToException(new Error(`Timed out waiting for SpacetimeDB connection after ` + timeoutMs$1.toString() + `ms`))), timeoutMs$1);
  });
  return Promise.race([
    connectPromise,
    timeoutPromise
  ]);
}

function configureServerConnection(config) {
  disconnectIfActive();
  serverConnectionConfig.contents = config;
  serverConnection.contents = undefined;
  serverConnectionPromise.contents = undefined;
}

function getConnection() {
  let config = serverConnectionConfig.contents;
  if (config === undefined) {
    return Stdlib_JsError.throwWithMessage("Server connection is not configured. Call configureServerConnection(config) first.");
  }
  let existingPromise = serverConnectionPromise.contents;
  if (existingPromise !== undefined) {
    return existingPromise;
  }
  let p = Stdlib_Promise.$$catch(connectServerConnection(config), error => {
    serverConnectionPromise.contents = undefined;
    throw error;
  });
  serverConnectionPromise.contents = p;
  return p;
}

function resetServerConnectionForTests() {
  disconnectIfActive();
  serverConnection.contents = undefined;
  serverConnectionConfig.contents = undefined;
  serverConnectionPromise.contents = undefined;
}

export {
  configureServerConnection,
  getConnection,
  resetServerConnectionForTests,
}
/* spacetimedb/sdk Not a pure module */
