// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

@module("@spacetimedb/rescript/react") @react.component
external make: (~connectionBuilder: StdbTypes.connectionBuilder, ~children: React.element) => React.element = "SpacetimeDBProvider"
