// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// Observer-backed hooks framework — no dependency on @spacetimedb/rescript/react.
//
// Provides:
//   - Connection context + Provider component
//   - Generic useRows / useCallWith / useCallUnit hooks
//   - Plain subscription helpers (no React)
//   - All React bindings go directly to "react", NOT through @spacetimedb/rescript/react.
//
// Schema-specific table/reducer configs live in {{self.root_module}}__Bridge.res.

module Sdk = {{self.root_module}}__Sdk
module Normalize = {{self.root_module}}__Normalize
module Client = {{self.root_module}}__Client
module Schema = {{self.root_module}}__Schema

// ── Minimal React bindings ────────────────────────────────────────────────────
// getServerSnapshot is required for SSR — without it React throws
// "Missing getServerSnapshot" during server rendering.
@module("react")
external useSyncExternalStore: (
  (unit => unit) => unit => unit,
  unit => 'a,
  ~getServerSnapshot: unit => 'a=?,
) => 'a = "useSyncExternalStore"

@module("react")
external useState: 'a => ('a, ('a => 'a) => unit) = "useState"

type reactRef<'a> = {mutable current: 'a}
@module("react")
external useRef: 'a => reactRef<'a> = "useRef"

// Mount-only effect: passes [] as deps so it runs once, not every render.
@module("react")
external useEffectOnMount: (unit => option<unit => unit>, @as(json`[]`) _) => unit = "useEffect"

@module("react")
external useMemo0: (unit => 'a) => 'a = "useMemo"

// ── Connection Context ────────────────────────────────────────────────────────

type connectionStore = {
  mutable conn: option<Sdk.connection<Sdk.remoteModule>>,
  mutable subscriptionReady: bool,
  mutable listeners: array<unit => unit>,
}

let connectionContext: React.Context.t<connectionStore> = React.createContext({
  conn: None,
  subscriptionReady: false,
  listeners: [],
})

module ConnectionProvider = {
  let make = connectionContext->React.Context.provider
}

let tokenKey = "stdb_token"
let identityKey = "stdb_identity"

@val @scope(("globalThis", "localStorage"))
external _getItem: string => Nullable.t<string> = "getItem"

@val @scope(("globalThis", "localStorage"))
external _setItem: (string, string) => unit = "setItem"

@val @scope(("globalThis", "localStorage"))
external _removeItem: string => unit = "removeItem"

module Provider = {
  @react.component
  let make = (~uri: string, ~moduleName: string, ~children: React.element) => {
    let store = useMemo0(() => ({
      conn: None,
      subscriptionReady: false,
      listeners: [],
    }: connectionStore))

    useEffectOnMount(() => {
      let savedToken = _getItem(tokenKey)->Nullable.toOption
      let notify = () => store.listeners->Array.forEach(fn => fn())
      let builder =
        Normalize.makeNormalizedBuilder(Schema.remoteModule, config =>
          Sdk.makeDbConnectionImpl(config)
        )
        ->Sdk.withUri(uri)
        ->Sdk.withDatabaseName(moduleName)
        ->Sdk.withToken(savedToken)
        ->Sdk.onConnect((conn, identity, authToken) => {
          _setItem(tokenKey, authToken)
          _setItem(identityKey, identity->Sdk.Identity.toHexString)
          // Connection available immediately (procedures work before subscription)
          store.conn = Some(conn)
          notify()
          // Subscribe to all non-event tables/views
          let queries = Schema.subscribableTableNames->Array.map(t => `SELECT * FROM ${t}`)
          conn
          ->Sdk.subscriptionBuilder
          ->Sdk.onApplied(_ctx => {
            store.subscriptionReady = true
            notify()
          })
          ->Sdk.onSubError((_ctx, _error) => {
            Console.error("SpacetimeDB subscription error")
          })
          ->Sdk.subscribe(queries)
          ->ignore
        })
        ->Sdk.onConnectError((_ctx, _error) => {
          switch savedToken {
          | Some(_) =>
            Console.warn("SpacetimeDB connect error with saved token - clearing")
            _removeItem(tokenKey)
          | None => ()
          }
        })

      builder->Sdk.buildConnection->ignore

      Some(
        () => {
          store.conn = None
          store.subscriptionReady = false
          notify()
        },
      )
    })

    <ConnectionProvider value=store> children </ConnectionProvider>
  }
}

let useConnection = (): option<Sdk.connection<Sdk.remoteModule>> => {
  let store = React.useContext(connectionContext)
  let subscribe = notify => {
    store.listeners = store.listeners->Array.concat([notify])
    () => {
      store.listeners = store.listeners->Array.filter(l => l !== notify)
    }
  }
  let getSnapshot = () => store.conn
  useSyncExternalStore(subscribe, getSnapshot, ~getServerSnapshot=() => None)
}

type connectionInfo = {isActive: bool, subscriptionReady: bool}

let useConnectionInfo = (): connectionInfo => {
  let conn = useConnection()
  let store = React.useContext(connectionContext)
  {isActive: conn->Option.isSome, subscriptionReady: store.subscriptionReady}
}

// ── Table config + generic useRows ────────────────────────────────────────────

type tableConfig<'row> = {
  getHandle: Sdk.connection<Sdk.remoteModule> => Obj.t,
  iter: Obj.t => Iterator.t<'row>,
}

type handleLike
@send external _onInsert: (handleLike, @uncurry (Obj.t, Obj.t) => unit) => unit = "onInsert"
@send
external _removeOnInsert: (handleLike, @uncurry (Obj.t, Obj.t) => unit) => unit = "removeOnInsert"
@send
external _onUpdate: (handleLike, @uncurry (Obj.t, Obj.t, Obj.t) => unit) => unit = "onUpdate"
@send
external _removeOnUpdate: (handleLike, @uncurry (Obj.t, Obj.t, Obj.t) => unit) => unit =
  "removeOnUpdate"
@send external _onDelete: (handleLike, @uncurry (Obj.t, Obj.t) => unit) => unit = "onDelete"
@send
external _removeOnDelete: (handleLike, @uncurry (Obj.t, Obj.t) => unit) => unit = "removeOnDelete"

external asHandleLike: Obj.t => handleLike = "%identity"

// Snapshot cache: only recompute .toArray() when version bumps.
// Returning the same array reference prevents useSyncExternalStore from
// seeing a "change" on every call (Object.is comparison).
type snapshotCache<'row> = {version: int, data: array<'row>}

let _emptyRows: array<Obj.t> = []
external _castRows: array<Obj.t> => array<'row> = "%identity"

let useRows = (config: tableConfig<'row>): array<'row> => {
  let conn = useConnection()
  let versionRef = useRef(0)
  let cachedRef: reactRef<snapshotCache<'row>> = useRef({version: -1, data: _castRows(_emptyRows)})

  // Keep conn in a ref so subscribe/getSnapshot closures stay stable.
  let connRef = useRef(conn)
  connRef.current = conn
  let cleanupRef: reactRef<unit => unit> = useRef(() => ())

  // Stable subscribe: reads connRef.current instead of capturing conn directly.
  // Built once via useMemo0 so useSyncExternalStore doesn't re-subscribe each render.
  let subscribe = useMemo0(() => {
    notify => {
      // Unsubscribe previous
      cleanupRef.current()

      switch connRef.current {
      | Some(c) =>
        let h = config.getHandle(c)->asHandleLike
        let bump = () => {
          versionRef.current = versionRef.current + 1
          notify()
        }
        let insertCb = (_ctx, _row) => bump()
        let updateCb = (_ctx, _prev, _next) => bump()
        let deleteCb = (_ctx, _row) => bump()
        h->_onInsert(insertCb)
        h->_onUpdate(updateCb)
        h->_onDelete(deleteCb)
        let cleanup = () => {
          h->_removeOnInsert(insertCb)
          h->_removeOnUpdate(updateCb)
          h->_removeOnDelete(deleteCb)
        }
        cleanupRef.current = cleanup
        cleanup
      | None =>
        cleanupRef.current = () => ()
        () => ()
      }
    }
  })

  let getSnapshot = () => {
    let v = versionRef.current
    if cachedRef.current.version !== v {
      cachedRef.current = {
        version: v,
        data: switch connRef.current {
        | Some(c) => config.iter(config.getHandle(c))->Iterator.toArray
        | None => _castRows(_emptyRows)
        },
      }
    }
    cachedRef.current.data
  }

  useSyncExternalStore(subscribe, getSnapshot, ~getServerSnapshot=() => _castRows(_emptyRows))
}

// ── Reducer mutation hooks ────────────────────────────────────────────────────

// Extract a human-readable message from any JS exception/error value.
let _exnToMessage: exn => string = %raw(`
  function(e) {
    if (e && typeof e.message === 'string') return e.message;
    if (typeof e === 'string') return e;
    try { return String(e); } catch(_) { return 'Unknown reducer error'; }
  }
`)

// Fire-and-forget: schedule microtask to call the promise error handler.
// This is the ONLY place the SDK's promise<unit> is consumed — entirely inside
// the infrastructure boundary, invisible to application code.
let _fireAndForget: (promise<unit>, exn => unit) => unit = %raw(`
  function(p, onError) { p.then(undefined, onError); }
`)

type reducerError = {
  message: string,
}

type mutationState<'args> = {
  call: 'args => unit,
  isPending: bool,
  error: option<reducerError>,
}

let useCallWith = (
  callReducer: (Sdk.connection<Sdk.remoteModule>, 'args) => promise<unit>,
): mutationState<'args> => {
  let conn = useConnection()
  let (isPending, setIsPending) = useState(false)
  let (error, setError) = useState(None)

  let call = args => {
    switch conn {
    | Some(c) =>
      setIsPending(_ => true)
      setError(_ => None)
      _fireAndForget(
        callReducer(c, args),
        e => {
          setIsPending(_ => false)
          setError(_ => Some({message: _exnToMessage(e)}))
        },
      )
    | None => Console.warn("Hooks.useCallWith: no connection")
    }
  }

  {call, isPending, error}
}

type mutationStateUnit = {
  call: unit => unit,
  isPending: bool,
  error: option<reducerError>,
}

let useCallUnit = (
  callReducer: Sdk.connection<Sdk.remoteModule> => promise<unit>,
): mutationStateUnit => {
  let conn = useConnection()
  let (isPending, setIsPending) = useState(false)
  let (error, setError) = useState(None)

  let call = () => {
    switch conn {
    | Some(c) =>
      setIsPending(_ => true)
      setError(_ => None)
      _fireAndForget(
        callReducer(c),
        e => {
          setIsPending(_ => false)
          setError(_ => Some({message: _exnToMessage(e)}))
        },
      )
    | None => Console.warn("Hooks.useCallUnit: no connection")
    }
  }

  {call, isPending, error}
}

// ── Procedure mutation hooks ──────────────────────────────────────────────────

type procedureState<'args, 'result> = {
  call: 'args => unit,
  isPending: bool,
  error: option<reducerError>,
  data: option<'result>,
}

let useCallProcedure = (
  callProc: (Sdk.connection<Sdk.remoteModule>, 'args) => promise<'result>,
): procedureState<'args, 'result> => {
  let conn = useConnection()
  let (isPending, setIsPending) = useState(false)
  let (error, setError) = useState(None)
  let (data, setData) = useState(None)

  let call = args => {
    switch conn {
    | Some(c) =>
      setIsPending(_ => true)
      setError(_ => None)
      setData(_ => None)
      _fireAndForget(
        callProc(c, args)->Promise.then(result => {
          setIsPending(_ => false)
          setData(_ => Some(result))
          Promise.resolve()
        }),
        e => {
          setIsPending(_ => false)
          setError(_ => Some({message: _exnToMessage(e)}))
        },
      )
    | None => Console.warn("Hooks.useCallProcedure: no connection")
    }
  }

  {call, isPending, error, data}
}

type procedureStateUnit<'result> = {
  call: unit => unit,
  isPending: bool,
  error: option<reducerError>,
  data: option<'result>,
}

let useCallProcedureUnit = (
  callProc: Sdk.connection<Sdk.remoteModule> => promise<'result>,
): procedureStateUnit<'result> => {
  let conn = useConnection()
  let (isPending, setIsPending) = useState(false)
  let (error, setError) = useState(None)
  let (data, setData) = useState(None)

  let call = () => {
    switch conn {
    | Some(c) =>
      setIsPending(_ => true)
      setError(_ => None)
      setData(_ => None)
      _fireAndForget(
        callProc(c)->Promise.then(result => {
          setIsPending(_ => false)
          setData(_ => Some(result))
          Promise.resolve()
        }),
        e => {
          setIsPending(_ => false)
          setError(_ => Some({message: _exnToMessage(e)}))
        },
      )
    | None => Console.warn("Hooks.useCallProcedureUnit: no connection")
    }
  }

  {call, isPending, error, data}
}

// ── Table config constructor ──────────────────────────────────────────────────

external toObj: 'a => Obj.t = "%identity"
external fromObj: Obj.t => 'a = "%identity"

let mkTable = (
  getHandle: Sdk.connection<Sdk.remoteModule> => 'handle,
  iter: 'handle => Iterator.t<'row>,
): tableConfig<'row> => {
  getHandle: conn => toObj(getHandle(conn)),
  iter: obj => iter(fromObj(obj)),
}

// ── Plain subscriptions (no React) ────────────────────────────────────────────
module Subscriptions = {
  let onTable = (
    handle: 'handle,
    ~onInsert: (Sdk.eventCtx, 'row) => unit,
    ~onUpdate: (Sdk.eventCtx, 'row, 'row) => unit,
    ~onDelete: (Sdk.eventCtx, 'row) => unit,
  ): (unit => unit) => {
    let h = toObj(handle)->asHandleLike
    let insertCb = (ctx, row) => onInsert(fromObj(ctx), fromObj(row))
    let updateCb = (ctx, prev, next) => onUpdate(fromObj(ctx), fromObj(prev), fromObj(next))
    let deleteCb = (ctx, row) => onDelete(fromObj(ctx), fromObj(row))
    h->_onInsert(insertCb)
    h->_onUpdate(updateCb)
    h->_onDelete(deleteCb)
    () => {
      h->_removeOnInsert(insertCb)
      h->_removeOnUpdate(updateCb)
      h->_removeOnDelete(deleteCb)
    }
  }
}
