// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// Observer-backed hooks framework — no dependency on @spacetimedb/rescript/react.
//
// Provides:
//   - Connection context + Provider component
//   - Generic useRows / useCallWith / useCallUnit hooks
//   - Plain subscription helpers (no React)
//   - All React bindings go directly to "react", NOT through @spacetimedb/rescript/react.
//
// Schema-specific table/reducer configs live in {{self.root_module}}__Bridge.res.

module Sdk = {{self.root_module}}__Sdk
module Client = {{self.root_module}}__Client
module Schema = {{self.root_module}}__Schema

// ── Minimal React bindings ────────────────────────────────────────────────────
@module("react")
external useSyncExternalStore: (
  (unit => unit) => unit => unit,
  unit => 'a,
) => 'a = "useSyncExternalStore"

@module("react")
external useState: 'a => ('a, ('a => 'a) => unit) = "useState"

type reactRef<'a> = {mutable current: 'a}
@module("react")
external useRef: 'a => reactRef<'a> = "useRef"

@module("react")
external useEffect0: (unit => option<unit => unit>) => unit = "useEffect"

@module("react")
external useMemo0: (unit => 'a) => 'a = "useMemo"

// ── Connection Context ────────────────────────────────────────────────────────

type connectionStore = {
  mutable conn: option<Sdk.connection>,
  mutable listeners: array<unit => unit>,
}

let connectionContext: React.Context.t<connectionStore> = React.createContext({
  conn: None,
  listeners: [],
})

module ConnectionProvider = {
  let make = connectionContext->React.Context.provider
}

let tokenKey = "stdb_token"

@val @scope(("globalThis", "localStorage"))
external _getItem: string => Nullable.t<string> = "getItem"

@val @scope(("globalThis", "localStorage"))
external _setItem: (string, string) => unit = "setItem"

@val @scope(("globalThis", "localStorage"))
external _removeItem: string => unit = "removeItem"

module Provider = {
  @react.component
  let make = (~uri: string, ~moduleName: string, ~children: React.element) => {
    let store = useMemo0(() => ({
      conn: None,
      listeners: [],
    }: connectionStore))

    useEffect0(() => {
      let savedToken = _getItem(tokenKey)->Nullable.toOption
      let builder =
        Sdk.makeDbConnectionBuilder(Schema.remoteModule, config =>
          Sdk.makeDbConnectionImpl(config)
        )
        ->Sdk.withUri(uri)
        ->Sdk.withDatabaseName(moduleName)
        ->Sdk.withToken(savedToken)
        ->Sdk.onConnect((_conn, _identity, authToken) => {
          _setItem(tokenKey, authToken)
        })
        ->Sdk.onConnectError((_ctx, _error) => {
          switch savedToken {
          | Some(_) =>
            Console.warn("SpacetimeDB connect error with saved token - clearing")
            _removeItem(tokenKey)
          | None => ()
          }
        })

      let conn = builder->Sdk.buildConnection
      store.conn = Some(conn)
      store.listeners->Array.forEach(fn => fn())

      Some(
        () => {
          store.conn = None
          store.listeners->Array.forEach(fn => fn())
        },
      )
    })

    <ConnectionProvider value=store> children </ConnectionProvider>
  }
}

let useConnection = (): option<Sdk.connection> => {
  let store = React.useContext(connectionContext)
  let subscribe = notify => {
    store.listeners = store.listeners->Array.concat([notify])
    () => {
      store.listeners = store.listeners->Array.filter(l => l !== notify)
    }
  }
  let getSnapshot = () => store.conn
  useSyncExternalStore(subscribe, getSnapshot)
}

type connectionInfo = {isActive: bool}

let useConnectionInfo = (): connectionInfo => {
  let conn = useConnection()
  {isActive: conn->Option.isSome}
}

// ── Table config + generic useRows ────────────────────────────────────────────

type tableConfig<'row> = {
  getHandle: Sdk.connection => Obj.t,
  iter: Obj.t => Iterator.t<'row>,
}

type handleLike
@send external _onInsert: (handleLike, @uncurry (Obj.t, Obj.t) => unit) => unit = "onInsert"
@send
external _removeOnInsert: (handleLike, @uncurry (Obj.t, Obj.t) => unit) => unit = "removeOnInsert"
@send
external _onUpdate: (handleLike, @uncurry (Obj.t, Obj.t, Obj.t) => unit) => unit = "onUpdate"
@send
external _removeOnUpdate: (handleLike, @uncurry (Obj.t, Obj.t, Obj.t) => unit) => unit =
  "removeOnUpdate"
@send external _onDelete: (handleLike, @uncurry (Obj.t, Obj.t) => unit) => unit = "onDelete"
@send
external _removeOnDelete: (handleLike, @uncurry (Obj.t, Obj.t) => unit) => unit = "removeOnDelete"

external asHandleLike: Obj.t => handleLike = "%identity"

let useRows = (config: tableConfig<'row>): array<'row> => {
  let conn = useConnection()
  let versionRef = useRef(0)

  let subscribe = notify => {
    switch conn {
    | Some(c) =>
      let h = config.getHandle(c)->asHandleLike
      let bump = () => {
        versionRef.current = versionRef.current + 1
        notify()
      }
      let insertCb = (_ctx, _row) => bump()
      let updateCb = (_ctx, _prev, _next) => bump()
      let deleteCb = (_ctx, _row) => bump()
      h->_onInsert(insertCb)
      h->_onUpdate(updateCb)
      h->_onDelete(deleteCb)
      () => {
        h->_removeOnInsert(insertCb)
        h->_removeOnUpdate(updateCb)
        h->_removeOnDelete(deleteCb)
      }
    | None => () => ()
    }
  }

  let getSnapshot = () => {
    let _ = versionRef.current
    switch conn {
    | Some(c) => config.iter(config.getHandle(c))->Iterator.toArray
    | None => []
    }
  }

  useSyncExternalStore(subscribe, getSnapshot)
}

// ── Reducer mutation hooks ────────────────────────────────────────────────────

type mutationState<'args> = {
  call: 'args => unit,
  isPending: bool,
  error: option<exn>,
}

let useCallWith = (
  callReducer: (Sdk.connection, 'args) => promise<unit>,
): mutationState<'args> => {
  let conn = useConnection()
  let (isPending, setIsPending) = useState(false)
  let (error, setError) = useState(None)

  let call = args => {
    switch conn {
    | Some(c) =>
      setIsPending(_ => true)
      setError(_ => None)
      callReducer(c, args)
      ->Promise.then(_ => {
        setIsPending(_ => false)
        Promise.resolve()
      })
      ->Promise.catch(e => {
        setIsPending(_ => false)
        setError(_ => Some(e))
        Promise.resolve()
      })
      ->ignore
    | None => Console.warn("Hooks.useCallWith: no connection")
    }
  }

  {call, isPending, error}
}

type mutationStateUnit = {
  call: unit => unit,
  isPending: bool,
  error: option<exn>,
}

let useCallUnit = (
  callReducer: Sdk.connection => promise<unit>,
): mutationStateUnit => {
  let conn = useConnection()
  let (isPending, setIsPending) = useState(false)
  let (error, setError) = useState(None)

  let call = () => {
    switch conn {
    | Some(c) =>
      setIsPending(_ => true)
      setError(_ => None)
      callReducer(c)
      ->Promise.then(_ => {
        setIsPending(_ => false)
        Promise.resolve()
      })
      ->Promise.catch(e => {
        setIsPending(_ => false)
        setError(_ => Some(e))
        Promise.resolve()
      })
      ->ignore
    | None => Console.warn("Hooks.useCallUnit: no connection")
    }
  }

  {call, isPending, error}
}

// ── Table config constructor ──────────────────────────────────────────────────

external toObj: 'a => Obj.t = "%identity"
external fromObj: Obj.t => 'a = "%identity"

let mkTable = (
  getHandle: Sdk.connection => 'handle,
  iter: 'handle => Iterator.t<'row>,
): tableConfig<'row> => {
  getHandle: conn => toObj(getHandle(conn)),
  iter: obj => iter(fromObj(obj)),
}

// ── Plain subscriptions (no React) ────────────────────────────────────────────
module Subscriptions = {
  let onTable = (
    handle: 'handle,
    ~onInsert: (Sdk.eventCtx, 'row) => unit,
    ~onUpdate: (Sdk.eventCtx, 'row, 'row) => unit,
    ~onDelete: (Sdk.eventCtx, 'row) => unit,
  ): (unit => unit) => {
    ignore((handle, onInsert, onUpdate, onDelete))
    () => ()
  }
}
