// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// Phantom types — query<'row> and reducerDef<'params> enforce type identity
// at the binding site. You cannot pass a receipt query where a booking query
// is expected — the compiler rejects it.
type query<'row>
type reducerDef<'params>

type connectionState = {
  isActive: bool,
  identity: option<string>,
  token: option<string>,
  connectionId: string,
}

type tableCallbacks<'row> = {
  onInsert?: 'row => unit,
  onDelete?: 'row => unit,
  onUpdate?: ('row, 'row) => unit,
}

@module("@spacetimedb/rescript/react")
external useTable: query<'row> => (array<'row>, bool) = "useTable"

@module("@spacetimedb/rescript/react")
external useTableWith: (query<'row>, tableCallbacks<'row>) => (array<'row>, bool) = "useTable"

@module("@spacetimedb/rescript/react")
external useReducer: reducerDef<'params> => ('params => promise<unit>) = "useReducer"

@module("@spacetimedb/rescript/react")
external useSpacetimeDB: unit => connectionState = "useSpacetimeDB"
