// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

module Sdk = Stdb__Sdk

// Phantom types — query<'row> and reducerDef<'params> enforce type identity
// at the binding site. You cannot pass a receipt query where a booking query
// is expected — the compiler rejects it.
type query<'row>
type reducerDef<'params>

type connectionState = {
  isActive: bool,
  identity: option<Sdk.identity>,
  token: option<string>,
  connectionId: Sdk.connectionId,
  connectionError: option<{message: string}>,
}

type tableCallbacks<'row> = {
  onInsert?: 'row => unit,
  onDelete?: 'row => unit,
  onUpdate?: ('row, 'row) => unit,
}

type rowsState<'row> =
  | Loading
  | Ready(array<'row>)

type mutationState<'args, 'error> = {
  call: 'args => unit,
  isPending: bool,
  error: option<'error>,
  reset: unit => unit,
}

@module("@spacetimedb/rescript/react")
external useTable: query<'row> => array<'row> = "useTable"

@module("@spacetimedb/rescript/react")
external useTableWith: (query<'row>, tableCallbacks<'row>) => array<'row> = "useTableWith"

@module("@spacetimedb/rescript/react")
external useTableState: query<'row> => rowsState<'row> = "useTableState"

@module("@spacetimedb/rescript/react")
external useReducer: reducerDef<'params> => ('params => 'effect) = "useReducer"

@module("@spacetimedb/rescript/react")
external useMutation: reducerDef<'args> => mutationState<'args, {message: string}> = "useMutation"

@module("@spacetimedb/rescript/react")
external useSpacetimeDB: unit => connectionState = "useSpacetimeDB"
