use crate::code_indenter::CodeIndenter;
use crate::OutputFile;
use spacetimedb_schema::def::ModuleDef;

use super::INDENT;

// ---------------------------------------------------------------------------
// StdbReact.res + SpacetimeDBProvider.res — React hook bindings.
//
// Phantom types `query<'row>` and `reducerDef<'params>` enforce type identity
// at the binding site: you cannot pass a receipt query where a booking query
// is expected — the compiler rejects it.
// ---------------------------------------------------------------------------

pub(super) fn generate_react_file(_module: &ModuleDef) -> Vec<OutputFile> {
    let mut output = CodeIndenter::new(String::new(), INDENT);
    let out = &mut output;

    writeln!(
        out,
        "// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE"
    );
    writeln!(
        out,
        "// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD."
    );
    writeln!(out, "");

    // Phantom types for type-safe React hook bindings
    writeln!(
        out,
        "// Phantom types — query<'row> and reducerDef<'params> enforce type identity"
    );
    writeln!(
        out,
        "// at the binding site. You cannot pass a receipt query where a booking query"
    );
    writeln!(out, "// is expected — the compiler rejects it.");
    writeln!(out, "type query<'row>");
    writeln!(out, "type reducerDef<'params>");
    writeln!(out, "");

    // Connection state
    writeln!(out, "type connectionState = {{");
    out.indent(1);
    writeln!(out, "isActive: bool,");
    writeln!(out, "identity: option<string>,");
    writeln!(out, "token: option<string>,");
    writeln!(out, "connectionId: string,");
    out.dedent(1);
    writeln!(out, "}}");
    writeln!(out, "");

    // Table callbacks
    writeln!(out, "type tableCallbacks<'row> = {{");
    out.indent(1);
    writeln!(out, "onInsert?: 'row => unit,");
    writeln!(out, "onDelete?: 'row => unit,");
    writeln!(out, "onUpdate?: ('row, 'row) => unit,");
    out.dedent(1);
    writeln!(out, "}}");
    writeln!(out, "");

    // React hook externals
    writeln!(out, "@module(\"@spacetimedb/rescript/react\")");
    writeln!(
        out,
        "external useTable: query<'row> => (array<'row>, bool) = \"useTable\""
    );
    writeln!(out, "");
    writeln!(out, "@module(\"@spacetimedb/rescript/react\")");
    writeln!(
        out,
        "external useTableWith: (query<'row>, tableCallbacks<'row>) => (array<'row>, bool) = \"useTable\""
    );
    writeln!(out, "");
    writeln!(out, "@module(\"@spacetimedb/rescript/react\")");
    writeln!(
        out,
        "external useReducer: reducerDef<'params> => ('params => promise<unit>) = \"useReducer\""
    );
    writeln!(out, "");
    writeln!(out, "@module(\"@spacetimedb/rescript/react\")");
    writeln!(
        out,
        "external useSpacetimeDB: unit => connectionState = \"useSpacetimeDB\""
    );

    let react_file = OutputFile {
        filename: "StdbReact.res".to_string(),
        code: output.into_inner(),
    };

    // SpacetimeDBProvider as separate component file
    let mut prov_output = CodeIndenter::new(String::new(), INDENT);
    let prov = &mut prov_output;

    writeln!(
        prov,
        "// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE"
    );
    writeln!(
        prov,
        "// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD."
    );
    writeln!(prov, "");
    writeln!(prov, "@module(\"@spacetimedb/rescript/react\") @react.component");
    writeln!(prov, "external make: (~connectionBuilder: StdbTypes.connectionBuilder, ~children: React.element) => React.element = \"SpacetimeDBProvider\"");

    let provider_file = OutputFile {
        filename: "SpacetimeDBProvider.res".to_string(),
        code: prov_output.into_inner(),
    };

    vec![react_file, provider_file]
}
