use crate::util::{
    collect_case, is_reducer_invokable, iter_constraints, iter_indexes, iter_procedures, iter_reducers, iter_tables,
    iter_types, iter_views,
};
use crate::{CodegenOptions, OutputFile};

use crate::code_indenter::{CodeIndenter, Indenter};
use crate::util::type_ref_name;

use convert_case::{Case, Casing};
use spacetimedb_lib::sats::layout::PrimitiveType;
use spacetimedb_lib::version::spacetimedb_lib_version;
use spacetimedb_primitives::ColId;
use spacetimedb_schema::def::{ConstraintDef, IndexDef, ModuleDef};
use spacetimedb_schema::identifier::Identifier;
use spacetimedb_schema::type_for_generate::{AlgebraicTypeDef, AlgebraicTypeUse};
use std::fmt::{self, Write};
use std::iter;
use std::ops::Deref;

// ---------------------------------------------------------------------------
// StdbSchema.mjs — pure JS runtime schema for the SpacetimeDB SDK.
//
// This file contains ONLY the REMOTE_MODULE object needed by the SDK for
// BSATN deserialization. No TypeScript, no types, no classes — just the
// runtime data that feeds `DbConnectionImpl` and `DbConnectionBuilder`.
//
// ReScript types live in StdbTypes.res (already generated). This file is the
// bridge between the ReScript world and the SDK's internal type system.
// ---------------------------------------------------------------------------

pub(super) fn generate_schema_file(module: &ModuleDef, options: &CodegenOptions) -> OutputFile {
    let mut output = CodeIndenter::new(String::new(), super::INDENT);
    let out = &mut output;

    let cli_version = spacetimedb_lib_version();
    writeln!(
        out,
        "// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB (ReScript codegen)."
    );
    writeln!(out, "// SpacetimeDB CLI Version: {cli_version}");
    writeln!(
        out,
        "// EDITS WILL NOT BE SAVED. MODIFY TABLES IN YOUR SERVER MODULE INSTEAD."
    );
    writeln!(out, "//");
    writeln!(out, "// Pure JS runtime schema — no TypeScript, no ReScript.");
    writeln!(out, "// Consumed by client.mjs and stdb-server.mjs as REMOTE_MODULE.");
    writeln!(out, "");
    writeln!(
        out,
        "import {{ schema, table, reducers as reducersBuilder, reducerSchema, procedures, procedureSchema, t, makeQueryBuilder, convertToAccessorMap }} from \"@spacetimedb/rescript\";"
    );
    writeln!(out, "");

    // --- Type builders (enums + objects) ---
    // These mirror types.ts but as plain JS const declarations.
    // Forward-reference handling: use `get` getters for Ref fields.

    let types: Vec<_> = iter_types(module).collect();
    if !types.is_empty() {
        writeln!(out, "// Type builders");
    }
    for ty in &types {
        let type_name = collect_case(Case::Pascal, ty.accessor_name.name_segments());
        match &module.typespace_for_generate()[ty.ty] {
            AlgebraicTypeDef::Product(product) => {
                write_schema_object_builder(module, out, &type_name, &product.elements);
            }
            AlgebraicTypeDef::Sum(sum) => {
                write_schema_enum_builder(module, out, &type_name, &sum.variants);
            }
            AlgebraicTypeDef::PlainEnum(plain_enum) => {
                let unit_variants: Vec<(Identifier, AlgebraicTypeUse)> = plain_enum
                    .variants
                    .iter()
                    .cloned()
                    .map(|var| (var, AlgebraicTypeUse::Unit))
                    .collect();
                write_schema_enum_builder(module, out, &type_name, &unit_variants);
            }
        }
    }
    if !types.is_empty() {
        writeln!(out, "");
    }

    // --- Table row builders ---
    writeln!(out, "// Table row builders");
    for table in iter_tables(module, options.visibility) {
        let type_ref = table.product_type_ref;
        let product_def = module.typespace_for_generate()[type_ref].as_product().unwrap();
        let row_name = format!("{}Row", table.accessor_name.deref().to_case(Case::Pascal));

        writeln!(out, "const {} = t.row({{", row_name);
        out.indent(1);
        write_schema_object_fields(module, out, &product_def.elements, table.primary_key, true, true);
        out.dedent(1);
        writeln!(out, "}});");
    }
    for view in iter_views(module) {
        let type_ref = view.product_type_ref;
        let product_def = module.typespace_for_generate()[type_ref].as_product().unwrap();
        let row_name = format!("{}Row", view.accessor_name.deref().to_case(Case::Pascal));

        writeln!(out, "const {} = t.row({{", row_name);
        out.indent(1);
        write_schema_object_fields(module, out, &product_def.elements, None, true, true);
        out.dedent(1);
        writeln!(out, "}});");
    }
    writeln!(out, "");

    // --- Reducer arg builders ---
    writeln!(out, "// Reducer arg builders");
    for reducer in iter_reducers(module, options.visibility) {
        if !is_reducer_invokable(reducer) {
            continue;
        }
        let args_name = format!("{}Args", reducer.accessor_name.deref().to_case(Case::Pascal));
        let elements = &reducer.params_for_generate.elements;

        write!(out, "const {} = {{", args_name);
        if elements.is_empty() {
            writeln!(out, "}};");
        } else {
            writeln!(out, "");
            out.indent(1);
            write_schema_object_fields(module, out, elements, None, true, false);
            out.dedent(1);
            writeln!(out, "}};");
        }
    }
    writeln!(out, "");

    // --- Procedure builders ---
    let procs: Vec<_> = iter_procedures(module, options.visibility).collect();
    if !procs.is_empty() {
        writeln!(out, "// Procedure builders");
        for procedure in &procs {
            let proc_name = format!("{}Proc", procedure.accessor_name.deref().to_case(Case::Pascal));
            let elements = &procedure.params_for_generate.elements;

            write!(out, "const {}_params = {{", proc_name);
            if elements.is_empty() {
                writeln!(out, "}};");
            } else {
                writeln!(out, "");
                out.indent(1);
                write_schema_object_fields(module, out, elements, None, true, false);
                out.dedent(1);
                writeln!(out, "}};");
            }

            write!(out, "const {}_returnType = ", proc_name);
            write_schema_type_builder(module, out, &procedure.return_type_for_generate).unwrap();
            writeln!(out, ";");
        }
        writeln!(out, "");
    }

    // --- REMOTE_MODULE assembly ---
    writeln!(out, "// Schema assembly");
    writeln!(out, "const tablesSchema = schema({{");
    out.indent(1);
    for table in iter_tables(module, options.visibility) {
        let type_ref = table.product_type_ref;
        let row_name = format!("{}Row", table.accessor_name.deref().to_case(Case::Pascal));

        writeln!(out, "{}: table({{", table.accessor_name);
        out.indent(1);
        write_schema_table_opts(
            module,
            out,
            type_ref,
            &table.name,
            iter_indexes(table),
            iter_constraints(table),
            table.is_event,
        );
        out.dedent(1);
        writeln!(out, "}}, {}),", row_name);
    }
    for view in iter_views(module) {
        let type_ref = view.product_type_ref;
        let row_name = format!("{}Row", view.accessor_name.deref().to_case(Case::Pascal));

        writeln!(out, "{}: table({{", view.accessor_name);
        out.indent(1);
        write_schema_table_opts(module, out, type_ref, &view.name, iter::empty(), iter::empty(), false);
        out.dedent(1);
        writeln!(out, "}}, {}),", row_name);
    }
    out.dedent(1);
    writeln!(out, "}});");
    writeln!(out, "");

    writeln!(out, "const reducersSchema = reducersBuilder(");
    out.indent(1);
    for reducer in iter_reducers(module, options.visibility) {
        if !is_reducer_invokable(reducer) {
            continue;
        }
        let args_name = format!("{}Args", reducer.accessor_name.deref().to_case(Case::Pascal));
        writeln!(out, "reducerSchema(\"{}\", {}),", reducer.name, args_name);
    }
    out.dedent(1);
    writeln!(out, ");");
    writeln!(out, "");

    writeln!(out, "const proceduresSchema = procedures(");
    out.indent(1);
    for procedure in &procs {
        let proc_name = format!("{}Proc", procedure.accessor_name.deref().to_case(Case::Pascal));
        writeln!(
            out,
            "procedureSchema(\"{}\", {}_params, {}_returnType),",
            procedure.name, proc_name, proc_name,
        );
    }
    out.dedent(1);
    writeln!(out, ");");
    writeln!(out, "");

    writeln!(out, "export const REMOTE_MODULE = {{");
    out.indent(1);
    writeln!(out, "versionInfo: {{");
    out.indent(1);
    writeln!(out, "cliVersion: \"{}\",", spacetimedb_lib_version());
    out.dedent(1);
    writeln!(out, "}},");
    writeln!(out, "tables: tablesSchema.schemaType.tables,");
    writeln!(out, "reducers: reducersSchema.reducersType.reducers,");
    writeln!(out, "...proceduresSchema,");
    out.dedent(1);
    writeln!(out, "}};");
    writeln!(out, "");
    writeln!(out, "export const tables = makeQueryBuilder(tablesSchema.schemaType);");
    writeln!(
        out,
        "export const reducers = convertToAccessorMap(reducersSchema.reducersType.reducers);"
    );

    OutputFile {
        filename: "StdbSchema.mjs".to_string(),
        code: output.into_inner(),
    }
}

/// Emit `const TypeName = t.object("TypeName", { ... });`
fn write_schema_object_builder(
    module: &ModuleDef,
    out: &mut Indenter,
    name: &str,
    elements: &[(Identifier, AlgebraicTypeUse)],
) {
    write!(out, "const {name} = t.object(\"{name}\", {{");
    if elements.is_empty() {
        writeln!(out, "}});");
    } else {
        writeln!(out, "");
        out.indent(1);
        write_schema_object_fields(module, out, elements, None, true, false);
        out.dedent(1);
        writeln!(out, "}});");
    }
}

/// Emit `const TypeName = t.enum("TypeName", { Variant: t.unit(), ... });`
fn write_schema_enum_builder(
    module: &ModuleDef,
    out: &mut Indenter,
    name: &str,
    variants: &[(Identifier, AlgebraicTypeUse)],
) {
    writeln!(out, "const {name} = t.enum(\"{name}\", {{");
    // Variant names in PascalCase (matching Rust enum variants)
    out.indent(1);
    for (variant_name, variant_type) in variants {
        let pascal = variant_name.deref().to_case(Case::Pascal);
        write_schema_type_builder_field(module, out, &pascal, None, variant_type, false);
    }
    out.dedent(1);
    writeln!(out, "}});");
}

/// Emit object/row fields with `get` getters for forward-referenced Ref types.
fn write_schema_object_fields(
    module: &ModuleDef,
    out: &mut Indenter,
    elements: &[(Identifier, AlgebraicTypeUse)],
    primary_key: Option<ColId>,
    convert_case: bool,
    write_original_name: bool,
) {
    for (i, (ident, ty)) in elements.iter().enumerate() {
        let name = if convert_case {
            ident.deref().to_case(Case::Camel)
        } else {
            ident.deref().into()
        };

        let is_primary_key = match primary_key {
            Some(pk) => pk.idx() == i,
            None => false,
        };
        let original_name = (write_original_name && convert_case && *name != **ident).then_some(&**ident);
        write_schema_type_builder_field(module, out, &name, original_name, ty, is_primary_key);
    }
}

/// Emit a single field, using `get` getter when the type references another type builder
/// (forward-reference pattern — valid JS, required for circular type graphs).
fn write_schema_type_builder_field(
    module: &ModuleDef,
    out: &mut Indenter,
    name: &str,
    original_name: Option<&str>,
    ty: &AlgebraicTypeUse,
    is_primary_key: bool,
) {
    let needs_getter = match ty {
        AlgebraicTypeUse::Ref(_) => true,
        AlgebraicTypeUse::Option(inner) | AlgebraicTypeUse::Array(inner) => {
            matches!(inner.as_ref(), AlgebraicTypeUse::Ref(_))
        }
        AlgebraicTypeUse::Result { ok_ty, err_ty } => {
            matches!(ok_ty.as_ref(), AlgebraicTypeUse::Ref(_)) || matches!(err_ty.as_ref(), AlgebraicTypeUse::Ref(_))
        }
        _ => false,
    };

    if needs_getter {
        writeln!(out, "get {name}() {{");
        out.indent(1);
        write!(out, "return ");
    } else {
        write!(out, "{name}: ");
    }
    write_schema_type_builder(module, out, ty).unwrap();
    if is_primary_key {
        // Custom domain types (Refs) don't have a .primaryKey() builder method in the JS SDK.
        if !matches!(ty, AlgebraicTypeUse::Ref(_)) {
            write!(out, ".primaryKey()");
        }
    }
    if let Some(original_name) = original_name {
        write!(out, ".name(\"{original_name}\")");
    }
    if needs_getter {
        writeln!(out, ";");
        out.dedent(1);
        writeln!(out, "}},");
    } else {
        writeln!(out, ",");
    }
}

/// Emit `t.u64()`, `t.option(t.string())`, `TypeName` (for Ref), etc.
fn write_schema_type_builder<W: Write>(module: &ModuleDef, out: &mut W, ty: &AlgebraicTypeUse) -> fmt::Result {
    match ty {
        AlgebraicTypeUse::Unit => write!(out, "t.unit()")?,
        AlgebraicTypeUse::Never => write!(out, "t.never()")?,
        AlgebraicTypeUse::Identity => write!(out, "t.identity()")?,
        AlgebraicTypeUse::ConnectionId => write!(out, "t.connectionId()")?,
        AlgebraicTypeUse::Timestamp => write!(out, "t.timestamp()")?,
        AlgebraicTypeUse::TimeDuration => write!(out, "t.timeDuration()")?,
        AlgebraicTypeUse::ScheduleAt => write!(out, "t.scheduleAt()")?,
        AlgebraicTypeUse::Uuid => write!(out, "t.uuid()")?,
        AlgebraicTypeUse::Option(inner_ty) => {
            write!(out, "t.option(")?;
            write_schema_type_builder(module, out, inner_ty)?;
            write!(out, ")")?;
        }
        AlgebraicTypeUse::Result { ok_ty, err_ty } => {
            write!(out, "t.result(")?;
            write_schema_type_builder(module, out, ok_ty)?;
            write!(out, ", ")?;
            write_schema_type_builder(module, out, err_ty)?;
            write!(out, ")")?;
        }
        AlgebraicTypeUse::Primitive(prim) => match prim {
            PrimitiveType::Bool => write!(out, "t.bool()")?,
            PrimitiveType::I8 => write!(out, "t.i8()")?,
            PrimitiveType::U8 => write!(out, "t.u8()")?,
            PrimitiveType::I16 => write!(out, "t.i16()")?,
            PrimitiveType::U16 => write!(out, "t.u16()")?,
            PrimitiveType::I32 => write!(out, "t.i32()")?,
            PrimitiveType::U32 => write!(out, "t.u32()")?,
            PrimitiveType::I64 => write!(out, "t.i64()")?,
            PrimitiveType::U64 => write!(out, "t.u64()")?,
            PrimitiveType::I128 => write!(out, "t.i128()")?,
            PrimitiveType::U128 => write!(out, "t.u128()")?,
            PrimitiveType::I256 => write!(out, "t.i256()")?,
            PrimitiveType::U256 => write!(out, "t.u256()")?,
            PrimitiveType::F32 => write!(out, "t.f32()")?,
            PrimitiveType::F64 => write!(out, "t.f64()")?,
        },
        AlgebraicTypeUse::String => write!(out, "t.string()")?,
        AlgebraicTypeUse::Array(elem_ty) => {
            if matches!(&**elem_ty, AlgebraicTypeUse::Primitive(PrimitiveType::U8)) {
                return write!(out, "t.byteArray()");
            }
            write!(out, "t.array(")?;
            write_schema_type_builder(module, out, elem_ty)?;
            write!(out, ")")?;
        }
        AlgebraicTypeUse::Ref(r) => {
            write!(out, "{}", type_ref_name(module, *r))?;
        }
    }
    Ok(())
}

/// Emit table options: name, indexes, constraints, event flag.
fn write_schema_table_opts<'a>(
    module: &ModuleDef,
    out: &mut Indenter,
    type_ref: spacetimedb_lib::sats::AlgebraicTypeRef,
    name: &Identifier,
    indexes: impl Iterator<Item = &'a IndexDef>,
    constraints: impl Iterator<Item = &'a ConstraintDef>,
    is_event: bool,
) {
    let product_def = module.typespace_for_generate()[type_ref].as_product().unwrap();
    writeln!(out, "name: '{}',", name.deref());
    writeln!(out, "indexes: [");
    out.indent(1);
    for index_def in indexes {
        if index_def.generated() {
            continue;
        }
        let columns = index_def.algorithm.columns();
        let get_name = |col_pos: spacetimedb_primitives::ColId| {
            let (field_name, _) = &product_def.elements[col_pos.idx()];
            field_name.deref().to_case(Case::Camel)
        };
        if let Some(accessor_name) = &index_def.accessor_name {
            writeln!(out, "{{ name: '{}', algorithm: 'btree', columns: [", accessor_name);
        } else {
            writeln!(out, "{{ name: '{}', algorithm: 'btree', columns: [", index_def.name);
        }
        out.indent(1);
        for col_id in columns.iter() {
            writeln!(out, "'{}',", get_name(col_id));
        }
        out.dedent(1);
        writeln!(out, "] }},");
    }
    out.dedent(1);
    writeln!(out, "],");
    writeln!(out, "constraints: [");
    out.indent(1);
    for constraint in constraints {
        let columns: Vec<_> = constraint
            .data
            .unique_columns()
            .into_iter()
            .flat_map(|cs| cs.iter())
            .map(|col_id| {
                let (field_name, _) = &product_def.elements[col_id.idx()];
                format!("'{}'", field_name.deref().to_case(Case::Camel))
            })
            .collect();

        writeln!(
            out,
            "{{ name: '{}', constraint: 'unique', columns: [{}] }},",
            constraint.name,
            columns.join(", ")
        );
    }
    out.dedent(1);
    writeln!(out, "],");
    if is_event {
        writeln!(out, "event: true,");
    }
}
